const createUserChatsSlice = (set, get) => ({
  directChats: [
    {
      name: 'Ahmed',
      username: 'ahmed',
      email: 'ahmed@example.com',
      id: 1,
      messages: [
        {
          userId: 1,
          id: 1,
          text: 'Hello',
          time: '12:00',
          type: 'text',
        },
        {
          userId: 9,
          id: 2,
          text: 'Hello, How are you?',
          time: '12:01',
          type: 'text',
        },
        {
          userId: 9,
          id: 3,
          text: 'And your family?',
          time: '12:02',
          type: 'text',
        },
        {
          userId: 1,
          id: 4,
          text: 'We are good',
          time: '12:03',
          type: 'text',
        },
        {
          userId: 9,
          id: 5,
          text: 'We are good too',
          time: '12:04',
          type: 'text',
        },
      ],
    },
    {
      name: 'Sarah',
      username: 'sarah',
      email: 'sarah@example.com',
      id: 2,
      messages: [
        {
          userId: 2,
          id: 1,
          text: 'Hey there!',
          time: '10:00',
          type: 'text',
        },
        {
          userId: 9,
          id: 2,
          text: 'Hi Sarah, how have you been?',
          time: '10:01',
          type: 'text',
        },
        {
          userId: 2,
          id: 3,
          text: "I'm doing great, thanks! How about you?",
          time: '10:02',
          type: 'text',
        },
        {
          userId: 9,
          id: 4,
          text: "I'm good too, thanks for asking!",
          time: '10:03',
          type: 'text',
        },
      ],
    },
    {
      name: 'John',
      username: 'john',
      email: 'john@example.com',
      id: 3,
      messages: [
        {
          userId: 3,
          id: 1,
          text: 'Morning!',
          time: '09:00',
          type: 'text',
        },
        {
          userId: 9,
          id: 2,
          text: 'Good morning John!',
          time: '09:01',
          type: 'text',
        },
        {
          userId: 3,
          id: 3,
          text: "How's your day going so far?",
          time: '09:02',
          type: 'text',
        },
        {
          userId: 9,
          id: 4,
          text: "It's going well, thanks!",
          time: '09:03',
          type: 'text',
        },
      ],
    },
    {
      name: 'Emily',
      username: 'emily',
      email: 'emily@example.com',
      id: 4,
      messages: [
        {
          userId: 4,
          id: 1,
          text: 'Hi!',
          time: '11:00',
          type: 'text',
        },
        {
          userId: 9,
          id: 2,
          text: 'Hello Emily, how are you?',
          time: '11:01',
          type: 'text',
        },
        {
          userId: 4,
          id: 3,
          text: "I'm good, thank you!",
          time: '11:02',
          type: 'text',
        },
        {
          userId: 9,
          id: 4,
          text: "That's great!",
          time: '11:03',
          type: 'text',
        },
      ],
    },
    {
      name: 'Michael',
      username: 'michael',
      email: 'michael@example.com',
      id: 5,
      messages: [
        {
          userId: 5,
          id: 1,
          text: 'Hey!',
          time: '08:00',
          type: 'text',
        },
        {
          userId: 9,
          id: 2,
          text: "Hi Michael, how's it going?",
          time: '08:01',
          type: 'text',
        },
        {
          userId: 5,
          id: 3,
          text: "I'm doing well, thanks!",
          time: '08:02',
          type: 'text',
        },
        {
          userId: 9,
          id: 4,
          text: 'Glad to hear that!',
          time: '08:03',
          type: 'text',
        },
      ],
    },
  ],
  groupChats: [],
  selectedChatType: null,
  selectedTabType: 'direct',
  selectedChat: null,
  selectedDetails: null,
  selectedChatMessages: null,
  setSelectedChatMessages: (messages) =>
    set(() => ({ selectedChatMessages: messages })),
  setSelectedDetails: (chat) => set(() => ({ selectedDetails: chat })),
  setSelectedChat: (chat) => set(() => ({ selectedChat: chat })),
  setSelectedChatType: (type) => set(() => ({ selectedChatsType: type })),
  setSelectedTabType: (type) => set(() => ({ selectedTabType: type })),
  addToDirectChats: (chat) =>
    set((state) => ({ directChats: [...state.get().directChats, chat] })),
  addToGroupChats: (chat) =>
    set((state) => ({ groupChats: [...state.get().groupChats, chat] })),
});

export default createUserChatsSlice;

